site_name: bookshelf
site_description: Inventory management for books.
repo_url: https://github.com/spkuehl/bookshelf-web
site_dir: site
copyright: Copyright &copy; 2018, <a href="https://github.com/spkuehl">spkuehl</a>.
dev_addr: 0.0.0.0:8001

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
