# Generated by Django 2.0.3 on 2018-03-12 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='renewel_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
