# Generated by Django 2.0.3 on 2018-03-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20180312_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
