# Generated by Django 2.0.3 on 2018-03-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='open_reservation',
            field=models.BooleanField(default=True),
        ),
    ]
