# Generated by Django 2.0.3 on 2018-04-20 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_reservation_open_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserve_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserve_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
