# Generated by Django 2.0.3 on 2018-04-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_auto_20180420_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='active_rental',
            field=models.BooleanField(default=True),
        ),
    ]
